In [1]:
import sys
sys.version

'3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]'

In [2]:
import tensorflow as tf
print(tf.__version__)

1.1.0


In [13]:
a = tf.constant(2)
b = tf.constant(3)
c=a+b
print(a)
print(a.dtype) 

Tensor("Const_22:0", shape=(), dtype=int32)
<dtype: 'int32'>


In [9]:
# 启动默认图
with tf.Session() as sess:
    print("a=2, b=3")
    print("常量加法: %i" % sess.run(a+b))
    print("常量乘法: %i" % sess.run(a*b))

a=2, b=3
常量加法: 5
常量乘法: 6


In [14]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
product = tf.matmul(matrix1, matrix2)
print(matrix1+matrix2)
print(product.get_shape().as_list())

Tensor("add_12:0", shape=(2, 2), dtype=float32)
[1, 1]


In [14]:
with tf.Session() as sess:
    result = sess.run(product)
    print(result)

[[ 12.]]


In [9]:
b=tf.constant([[1,2,3],[4,5,6]])
b_shape=b.get_shape()
b_shape
#print(b_shape[0].value,b_shape[1].value)



TensorShape([Dimension(2), Dimension(3)])

In [24]:
a=tf.zeros([2,3],tf.int32)

In [25]:
with tf.Session() as sess:
    print(sess.run(a))

[[0 0 0]
 [0 0 0]]


In [32]:
a = tf.zeros([3, 2])
W = tf.Variable(a) 

In [33]:
with tf.Session() as sess: 
    print(sess.run(a))
    sess.run(W.initializer)
    print(W)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
Tensor("Variable_3/read:0", shape=(3, 2), dtype=float32)


In [4]:
help(tf.concat)

Help on function concat in module tensorflow.python.ops.array_ops:

concat(values, axis, name='concat')
    Concatenates tensors along one dimension.
    
    Concatenates the list of tensors `values` along dimension `axis`.  If
    `values[i].shape = [D0, D1, ... Daxis(i), ...Dn]`, the concatenated
    result has shape
    
        [D0, D1, ... Raxis, ...Dn]
    
    where
    
        Raxis = sum(Daxis(i))
    
    That is, the data from the input tensors is joined along the `axis`
    dimension.
    
    The number of dimensions of the input tensors must match, and all dimensions
    except `axis` must be equal.
    
    For example:
    
    ```python
    t1 = [[1, 2, 3], [4, 5, 6]]
    t2 = [[7, 8, 9], [10, 11, 12]]
    tf.concat([t1, t2], 0) ==> [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
    tf.concat([t1, t2], 1) ==> [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]
    
    # tensor t3 with shape [2, 3]
    # tensor t4 with shape [2, 3]
    tf.shape(tf.concat([t3, t4], 0)) ==> [